name: "ensure_compile_and_run"
description: "Ensure the project builds and runs"
runs:
  using: docker
  # .github/workflows/main.yaml copies the Dockerfile here
  image: ../../../../_ci/compile_and_run/Dockerfile