name: Code Coverage
on:
  pull_request:

permissions:
  contents: read  # for actions/checkout to fetch code

jobs:
  bazel_build:
    name: Bazel - Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build via bazel
        run: bazel build //...
  
  code_coverage:
    name: Bazel - Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Run bazel code-coverage
        run: bazel coverage --nocache_test_results ...:all