name: Lint and Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: copy dockerfile
        # awful hack because COPY ../ doesn't work in Dockerfile
        # https://github.com/actions/runner/issues/2017
        run: cp ./_ci/lint/Dockerfile ./Dockerfile
      - name: lint
        uses: ./.github/workflows/actions/lint/

  bazel_tests:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    name: Bazel - Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build via bazel
        run: bazel build //...
      - name: Test via bazel
        run: bazel test //...
