on: [pull_request]
jobs:
  bazel_build:
    container:
      options: --user root
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: copy dockerfile
        # awful hack because COPY ../ doesn't work in Dockerfile
        # https://github.com/actions/runner/issues/2017
        run: cp ./_ci/bazel_build/Dockerfile ./Dockerfile
      - name: bazel_build
        uses: ./.github/workflows/actions/bazel_build/
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: copy dockerfile
        # awful hack because COPY ../ doesn't work in Dockerfile
        # https://github.com/actions/runner/issues/2017
        run: cp ./_ci/lint/Dockerfile ./Dockerfile
      - name: lint
        uses: ./.github/workflows/actions/lint/
