on: [pull_request]
jobs:
  bazel_build:
    container:
      image: gcr.io/bazel-public/bazel:latest@sha256:91d0c1fcbb9e46c562dab1b99eba360188fe5d1e2890f502b7af509219a3ff5d
      options: --user ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: copy dockerfile
        # awful hack because COPY ../ doesn't work in Dockerfile
        # https://github.com/actions/runner/issues/2017
        run: cp ./_ci/bazel_build/Dockerfile ./Dockerfile
      - name: bazel_build
        uses: ./.github/workflows/actions/bazel_build/
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: copy dockerfile
        # awful hack because COPY ../ doesn't work in Dockerfile
        # https://github.com/actions/runner/issues/2017
        run: cp ./_ci/lint/Dockerfile ./Dockerfile
      - name: lint
        uses: ./.github/workflows/actions/lint/
