on: [pull_request]
jobs:
  ensure_compile_and_run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: copy dockerfile
        # awful hack because COPY ../ doesn't work in Dockerfile
        # https://github.com/actions/runner/issues/2017
        run: cp ./_ci/compile_and_run/Dockerfile ./Dockerfile
      - name: compile and run
        uses: ./.github/workflows/actions/ensure_compile_and_run/
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: copy dockerfile
        # awful hack because COPY ../ doesn't work in Dockerfile
        # https://github.com/actions/runner/issues/2017
        run: cp ./_ci/lint/Dockerfile ./Dockerfile
      - name: lint
        uses: ./.github/workflows/actions/lint/
